/* =========================================================
   GRAMMAR PRO — 克漏字大題庫產生器（cloze2.js）
   20 題框 × 每格 2 文法變體 × 6 詞彙組 = 240 篇 / 960 格
   加上 cloze.js 手寫 12 篇 = 252 篇 / 1,008 格
   每個考點的選項與詳解皆手寫；答案由規則決定，保證正確
   ========================================================= */
(function(){
  const OUT=[];

  /* 整句插入題的「離題」誘答句庫（依序輪替取 3 句） */
  const OFF_BIZ=[
    "Our company was founded nearly a century ago by two brothers.",
    "The cafeteria menu changes every Monday.",
    "The parking lot will be repainted in bright yellow.",
    "Employees may bring their pets to the rooftop garden.",
    "The weather has been lovely this week.",
    "My favorite season has always been early autumn.",
    "The office plants are watered twice a week.",
    "A new coffee shop opened across the street last month."
  ];
  const OFF_GEN=[
    "The cafeteria was painted green last summer.",
    "My uncle lives near the train station.",
    "Water boils at 100 degrees Celsius.",
    "The library has a large collection of old maps.",
    "His bicycle is the same color as mine.",
    "Whales are the largest animals on Earth.",
    "The bakery on the corner sells fresh bread every morning.",
    "Our neighbor grows tomatoes on her balcony."
  ];
  const off=(pool,i)=>[pool[i%pool.length],pool[(i+2)%pool.length],pool[(i+4)%pool.length]];

  /* ================= 題框定義 ================= */
  const FRAMES=[

  /* ---------- TOEIC ① 訂單出貨通知 (lv1) ---------- */
  { kind:"toeic", cat:"biz", lv:1,
    title:v=>"出貨通知："+v.itemZh,
    lex:[
      {name:"Ms. Carter",item:"wireless headphones",itemZh:"無線耳機",time:"yesterday",days:"three"},
      {name:"Mr. Lin",item:"coffee machine",itemZh:"咖啡機",time:"this morning",days:"two"},
      {name:"Ms. Gomez",item:"desk lamp",itemZh:"桌燈",time:"last night",days:"five"},
      {name:"Mr. Baker",item:"laptop stand",itemZh:"筆電架",time:"on Monday",days:"four"},
      {name:"Ms. Rossi",item:"electric kettle",itemZh:"快煮壺",time:"two days ago",days:"three"},
      {name:"Mr. Patel",item:"office chair",itemZh:"辦公椅",time:"last Friday",days:"seven"}
    ],
    intro:v=>`Dear ${v.name},\n\nThank you for your recent order.`,
    outro:()=>"Best regards,\nSwift Shopping Team",
    slots:[
      [ v=>({s:`Your ${v.item} {N} ${v.time} and should arrive within ${v.days} business days.`,
             c:"was shipped",d:["has been shipped","is being shipped","will be shipped"],
             ex:`「${v.time}」是明確的過去時間，且 ${v.item} 是「被寄出」的對象，用過去式被動 was shipped。誘答拆解：has been shipped 是現在完成式，不能和明確過去時間並用；is being shipped 表「此刻正在被寄」；will be shipped 是未來式——三者都與 ${v.time} 矛盾。`}),
        v=>({s:`Your ${v.item} {N} carefully and is now ready for delivery.`,
             c:"has been packed",d:["has packed","is packing","packed"],
             ex:`商品是「被包裝」的對象（被動），且句尾 is now ready 顯示動作已完成並影響現在，用現在完成式被動 has been packed。誘答拆解：has packed 與 is packing 都是主動（商品不會自己包裝）；packed 單獨的過去式少了與「現在」的連結。`}) ],
      [ v=>({s:"Once the package arrives, please check the items {N}.",
             c:"carefully",d:["careful","carefulness","more careful"],
             ex:"修飾動詞 check（檢查的「方式」）要用副詞 carefully。誘答拆解：careful 是形容詞，只能修飾名詞或放在 be 動詞後；carefulness 是名詞；more careful 是形容詞比較級，這裡沒有比較對象。"}),
        v=>({s:"Please make sure the shipping address on the label is {N}.",
             c:"correct",d:["correctly","correctness","correction"],
             ex:"be 動詞 is 後面接「形容詞」當補語，描述主詞 address 的狀態：is correct（是正確的）。誘答拆解：correctly 是副詞，不能當補語；correctness、correction 是名詞，語意不通（地址＝正確性？）。"}) ],
      [ v=>({s:"If anything is missing, contact our service team {N} 24 hours.",
             c:"within",d:["until","since","at"],
             ex:"within + 一段時間＝「在…之內」：within 24 hours 24 小時內。誘答拆解：until 是「直到某時間點為止」；since 是「自某起點以來」（要搭完成式）；at 接精確時刻（at 3 p.m.），不接一段時間。"}),
        v=>({s:"You can track your order at any time {N} our mobile app.",
             c:"through",d:["among","onto","beside"],
             ex:"表「透過（管道／工具）」用 through：through our app 透過我們的 App。誘答拆解：among 是「在三者以上之間」；onto 是「到…上面」；beside 是「在旁邊」——都與「管道」無關。"}) ],
      [ v=>({s:"{N}",
             c:"We appreciate your business and hope to serve you again soon.",d:off(OFF_BIZ,0),
             ex:"整句插入題：這封信的主旨是「訂單出貨通知」，收尾應呼應主旨——感謝惠顧、期待再次服務。其他選項（公司歷史、餐廳菜單、天氣）都與出貨情境完全無關，屬於「離題」誘答。"}),
        v=>({s:"{N}",
             c:"Thank you again for choosing our store.",d:off(OFF_BIZ,1),
             ex:"整句插入題：判斷關鍵是「這句話放進文章裡通不通」。感謝顧客選擇本店＝購物信件的自然收尾；其餘選項與訂單、出貨毫無關聯，放進來會顯得突兀。"}) ]
    ]},

  /* ---------- TOEIC ② 會議改期通知 (lv2) ---------- */
  { kind:"toeic", cat:"biz", lv:2,
    title:v=>"會議通知："+v.mtgZh,
    lex:[
      {mtg:"monthly sales meeting",mtgZh:"月度業務會議",day:"Friday, June 12",time2:"10 a.m.",person:"Mr. Lopez"},
      {mtg:"staff training session",mtgZh:"員工訓練",day:"Wednesday, March 5",time2:"2 p.m.",person:"Ms. Chen"},
      {mtg:"budget review",mtgZh:"預算檢討會",day:"Monday, April 14",time2:"9 a.m.",person:"Mr. Weber"},
      {mtg:"product briefing",mtgZh:"產品說明會",day:"Thursday, July 3",time2:"3 p.m.",person:"Ms. Ito"},
      {mtg:"quarterly review",mtgZh:"季度檢討會",day:"Tuesday, October 7",time2:"11 a.m.",person:"Mr. Silva"},
      {mtg:"safety workshop",mtgZh:"工安講習",day:"Friday, August 22",time2:"1 p.m.",person:"Ms. Park"}
    ],
    intro:()=>"To: All Staff",
    outro:()=>"Management Office",
    slots:[
      [ v=>({s:`Please note that the ${v.mtg} {N} to ${v.day} at ${v.time2}`,
             c:"has been moved",d:["has moved","is moving","moves"],
             ex:"會議是「被移動」時間的對象（人移動會議，不是會議自己移動），且改期的結果影響現在，用現在完成式被動 has been moved。誘答拆解：has moved／is moving／moves 都是主動語態，主詞會議不會自己執行動作。"}),
        v=>({s:`Please note that the ${v.mtg} {N} until further notice.`,
             c:"has been postponed",d:["has postponed","is postponing","postpones"],
             ex:"會議是「被延期」的對象，用現在完成式被動 has been postponed（已被延期、效果持續到現在）。誘答拆解：三個主動選項都把會議當成執行者，語意不通；until further notice（直到另行通知）是延期公告的固定搭配。"}) ],
      [ v=>({s:"The change was made because the conference room is {N} renovated.",
             c:"being",d:["been","be","to be"],
             ex:"現在進行式被動＝ is + being + p.p.：「正在被整修」。誘答拆解：been 用於完成式（has been done）；be 原形不能直接接在 is 後面；to be 是不定詞，這裡沒有接不定詞的結構。"}),
        v=>({s:"The room cannot be used {N} the ongoing repairs.",
             c:"because of",d:["because","although","so that"],
             ex:"後面接的是名詞片語 the ongoing repairs（不是完整句子），所以用介系詞片語 because of。誘答拆解：because 要接「主詞＋動詞」的子句；although 表讓步且也需接子句；so that 表目的，語意與結構都不合。"}) ],
      [ v=>({s:"Kindly review the attached report before {N} the meeting.",
             c:"attending",d:["attend","to attend","attended"],
             ex:"這裡的 before 是介系詞，介系詞後面的動詞一律用動名詞 V-ing：before attending。誘答拆解：attend 原形與 attended 過去式都不能直接接在介系詞後；to attend 是不定詞，介系詞後不接 to V。"}),
        v=>({s:"All managers are expected {N} the updated agenda in advance.",
             c:"to read",d:["reading","read","reads"],
             ex:"be expected to V＝「被期待／被要求去做」，固定接不定詞：are expected to read。誘答拆解：expect 的被動語態後面只能接 to V，reading／read／reads 都不符合這個固定句型。"}) ],
      [ v=>({s:`Employees {N} have questions should email ${v.person} in advance.`,
             c:"who",d:["whose","which","whom"],
             ex:"先行詞 Employees 指「人」，且在關係子句中當「主詞」（___ have questions），用主格 who。誘答拆解：whose 是所有格（後面要接名詞）；which 只能指物；whom 是受格，不能當子句主詞。"}),
        v=>({s:`Anyone {N} schedule conflicts with the new time should inform ${v.person}.`,
             c:"whose",d:["who","which","whom"],
             ex:"空格後面直接接名詞 schedule（＝「他的」行程），表所有關係用 whose。誘答拆解：who／whom 後面不能直接接名詞當「誰的…」；which 指物且同樣沒有所有格功能（要用 of which）。"}) ]
    ]},

  /* ---------- TOEIC ③ 面試邀請 (lv2) ---------- */
  { kind:"toeic", cat:"biz", lv:2,
    title:v=>"面試邀請："+v.posZh,
    lex:[
      {pos:"marketing",posZh:"行銷職缺",day:"May 3",time2:"2 p.m."},
      {pos:"accounting",posZh:"會計職缺",day:"June 10",time2:"10 a.m."},
      {pos:"design",posZh:"設計職缺",day:"April 21",time2:"3 p.m."},
      {pos:"sales",posZh:"業務職缺",day:"March 18",time2:"9 a.m."},
      {pos:"engineering",posZh:"工程職缺",day:"July 7",time2:"1 p.m."},
      {pos:"customer service",posZh:"客服職缺",day:"August 15",time2:"11 a.m."}
    ],
    intro:v=>`Dear Applicant,\n\nThank you for applying for the ${v.pos} position.`,
    outro:()=>"Sincerely,\nTalent Team",
    slots:[
      [ v=>({s:`We were impressed by your resume and {N} to invite you to an interview on ${v.day} at ${v.time2}`,
             c:"would like",d:["are liking","would rather","had liked"],
             ex:"would like to V＝「想要…」的客氣說法，是商用書信標準用語。誘答拆解：like 是狀態動詞，不用進行式（are liking ✗）；would rather 後面接原形不接 to；had liked 過去完成式在此無「更早的過去」可對照。"}),
        v=>({s:`Your interview {N} for ${v.day} at ${v.time2} at our head office.`,
             c:"has been scheduled",d:["has scheduled","is scheduling","schedules"],
             ex:"面試是「被安排」的對象，用現在完成式被動 has been scheduled（已排定、現在有效）。誘答拆解：三個主動選項都把 interview 當成執行者——面試不會自己安排自己。"}) ],
      [ v=>({s:"Should you {N} to reschedule, please call our HR office two days in advance.",
             c:"need",d:["needed","needing","to need"],
             ex:"Should you need…＝If you should need… 省略 if 的倒裝假設句，should 之後接原形動詞 need。誘答拆解：needed／needing／to need 都不能接在助動詞 should 後面（助動詞＋原形是鐵律）。"}),
        v=>({s:"If you {N} any questions before the interview, feel free to email us.",
             c:"have",d:["will have","had had","would have"],
             ex:"第一類條件句：if 子句用「現在式」表未來可能（if you have questions），主句用祈使或 will。誘答拆解：if 子句不放 will（will have ✗）；had had 是過去完成式、would have 是與過去相反的假設，時態都不符。"}) ],
      [ v=>({s:"We look forward to {N} you in person.",
             c:"meeting",d:["meet","to meet","met"],
             ex:"look forward to 的 to 是「介系詞」不是不定詞，後面接 V-ing：look forward to meeting。誘答拆解：meet 原形與 met 過去式不能接在介系詞後；to meet 會變成 to to meet 的重複錯誤。這是多益的超高頻考點。"}),
        v=>({s:"Please remember {N} two copies of your portfolio to the interview.",
             c:"to bring",d:["bringing","bring","brought"],
             ex:"remember to V＝記得「去做」（還沒做的事）；remember V-ing＝記得「做過」。面試還沒發生，要提醒對方帶作品集，用 to bring。誘答拆解：bringing 意思變成「記得帶過」；bring／brought 缺少 to，不成句型。"}) ],
      [ v=>({s:"Please arrive ten minutes early so that we {N} start on time.",
             c:"can",d:["could have","must","should have"],
             ex:"so that + S + can/could V＝「以便能夠…」表目的；主句是現在的請求，用 can。誘答拆解：could have／should have + p.p. 是對「過去」的推測或懊悔；must 表義務，與「目的」句型不搭。"}),
        v=>({s:"Interviews {N} in the meeting room on the second floor.",
             c:"will be held",d:["will hold","are holding","held"],
             ex:"面試是「被舉行」的，未來的安排用未來式被動 will be held。誘答拆解：will hold／are holding 是主動（面試不會自己舉行）；held 單獨過去式與未來的安排矛盾。"}) ],
    ].slice(0,4).concat([[
        v=>({s:"{N}",
             c:"Please confirm your attendance by Friday.",d:off(OFF_BIZ,2),
             ex:"整句插入題：面試邀請信的合理收尾＝請對方「確認出席」。其他選項（停車場、寵物、天氣）與面試流程無關，一放進去就破壞信件邏輯。"}),
        v=>({s:"{N}",
             c:"We wish you the best of luck and hope to see you soon.",d:off(OFF_BIZ,3),
             ex:"整句插入題：對應徵者的祝福＋期待見面，是邀請信自然的結尾語氣。其餘選項皆為與面試無關的「離題」句。"}) ]]).slice(0,4)
  },

  /* ---------- TOEIC ④ 商店促銷公告 (lv1) ---------- */
  { kind:"toeic", cat:"biz", lv:1,
    title:v=>"促銷公告："+v.storeZh,
    lex:[
      {store:"Green Mart",storeZh:"超市",month:"next month",amt:"50",day:"Sunday",adjB:"cheap",adjC:"cheaper",adjS:"cheapest"},
      {store:"Book Corner",storeZh:"書店",month:"this spring",amt:"30",day:"Saturday",adjB:"big",adjC:"bigger",adjS:"biggest"},
      {store:"Tech Plaza",storeZh:"3C 賣場",month:"next week",amt:"100",day:"Friday",adjB:"light",adjC:"lighter",adjS:"lightest"},
      {store:"Home Style",storeZh:"家居館",month:"in July",amt:"80",day:"Sunday",adjB:"fresh",adjC:"fresher",adjS:"freshest"},
      {store:"Sport Zone",storeZh:"運動用品店",month:"next month",amt:"60",day:"Saturday",adjB:"small",adjC:"smaller",adjS:"smallest"},
      {store:"Daily Deli",storeZh:"食品舖",month:"this weekend",amt:"40",day:"Friday",adjB:"sweet",adjC:"sweeter",adjS:"sweetest"}
    ],
    intro:()=>"Attention Shoppers:",
    outro:v=>`${v.store} Management`,
    slots:[
      [ v=>({s:`Starting ${v.month}, our store {N} open until 11 p.m. on weekends.`,
             c:"will be",d:["being","is being","be"],
             ex:`Starting ${v.month} 指向未來；open 在此是形容詞（營業中的狀態），未來的狀態用 will be open。誘答拆解：being／be 不能單獨當述語；is being open 的進行式與「常態的營業時間」語意矛盾。`}),
        v=>({s:"A grand reopening sale {N} this Saturday at 9 a.m.",
             c:"will be held",d:["will hold","holds","is holding"],
             ex:"特賣會是「被舉辦」的對象，未來的活動用未來式被動 will be held。誘答拆解：will hold／holds／is holding 都是主動語態——sale 不會自己舉辦自己，缺了 be + p.p. 就不是被動。"}) ],
      [ v=>({s:`Customers {N} spend more than $${v.amt} will receive a free gift.`,
             c:"who",d:["whose","which","whom"],
             ex:"先行詞 Customers 指人、且在子句中當主詞（___ spend…），用主格 who。誘答拆解：whose 後面要接名詞表「誰的」；which 指物；whom 是受格不能當主詞。"}),
        v=>({s:"Members can enjoy discounts {N} are not available to regular shoppers.",
             c:"that",d:["who","whose","where"],
             ex:"先行詞 discounts 是「物」且子句缺主詞，用 that（或 which）。誘答拆解：who 只能指人；whose 是所有格；where 是關係副詞，只能接「完整句子」，但這裡子句缺主詞。"}) ],
      [ v=>({s:`This month's special set is even {N} than last year's version.`,
             c:v.adjC,d:[v.adjB,v.adjS,"more "+v.adjB],
             ex:`句中有 than（比較對象），要用比較級 ${v.adjC}；even 用來加強比較級（甚至更…）。誘答拆解：${v.adjB} 是原級不能配 than；${v.adjS} 是最高級；more ${v.adjB} 犯了「-er 與 more 並用」的重複錯誤——短音節形容詞直接加 -er。`}),
        v=>({s:"It is one of the {N} deals we have ever offered.",
             c:"best",d:["better","good","well"],
             ex:"one of the + 最高級 + 複數名詞＝「最…之一」；good 的最高級是 best。誘答拆解：better 是比較級（要有 than）；good 原級不能接在 the 後表「最」；well 是副詞。"}) ],
      [ v=>({s:`Don't miss this chance—visit us {N} ${v.day}!`,
             c:"on",d:["in","at","by"],
             ex:`星期幾（${v.day}）前面用介系詞 on。誘答拆解：in 接月份、年份、季節等大範圍；at 接精確時刻（at 9 a.m.）；by 是「在…之前」表期限，語意不合。`}),
        v=>({s:"{N}",
             c:"We look forward to seeing you at the store.",d:off(OFF_BIZ,4),
             ex:"整句插入題：促銷公告的目的是吸引顧客上門，收尾用「期待您的光臨」最呼應主旨。其他選項與購物、促銷情境完全無關。"}) ]
    ]},

  /* ---------- TOEIC ⑤ 退換貨回覆 (lv2) ---------- */
  { kind:"toeic", cat:"biz", lv:2,
    title:v=>"客服回覆："+v.itemZh,
    lex:[
      {item:"coffee maker",itemZh:"咖啡機",card:"credit card"},
      {item:"blender",itemZh:"果汁機",card:"debit card"},
      {item:"vacuum cleaner",itemZh:"吸塵器",card:"credit card"},
      {item:"hair dryer",itemZh:"吹風機",card:"gift card"},
      {item:"toaster",itemZh:"烤麵包機",card:"credit card"},
      {item:"electric heater",itemZh:"電暖器",card:"debit card"}
    ],
    intro:v=>`Dear Customer,\n\nWe are sorry to hear that your ${v.item} stopped working.`,
    outro:()=>"Customer Care Team",
    slots:[
      [ v=>({s:"If the item {N} within 30 days, you can get a full refund.",
             c:"is returned",d:["returns","returned","will be returned"],
             ex:"第一類條件句的 if 子句用「現在式」；商品是「被退回」的對象，所以是現在式被動 is returned。誘答拆解：returns 是主動（商品不會自己退貨）；returned 缺 be 動詞不成被動；if 子句不用未來式（will be returned ✗）。"}),
        v=>({s:`Since your ${v.item} is still under warranty, we {N} it free of charge.`,
             c:"will replace",d:["would have replaced","used to replace","had replaced"],
             ex:"依據保固條件承諾「接下來會做」的事，用未來式 will replace。誘答拆解：would have replaced 是與過去相反的假設；used to 是過去的習慣；had replaced 是過去完成式——三者都不能表達未來的承諾。"}) ],
      [ v=>({s:"A replacement {N} to your address within five business days.",
             c:"will be delivered",d:["will deliver","delivers","is delivering"],
             ex:"新品是「被寄送」的對象，未來動作用未來式被動 will be delivered。誘答拆解：will deliver／delivers／is delivering 都是主動——replacement 不會自己寄送自己，必須有 be + p.p.。"}),
        v=>({s:`Your refund {N} to your ${v.card} already.`,
             c:"has been issued",d:["has issued","is issuing","issues"],
             ex:"already（已經）是完成式的訊號字；退款是「被核發」的對象，用現在完成式被動 has been issued。誘答拆解：三個主動選項都缺 been——refund 是被處理的對象，不是執行者。"}) ],
      [ v=>({s:"Please pack the item {N} its original box before sending it back.",
             c:"in",d:["on","at","for"],
             ex:"裝「在盒子裡面」＝容器內部，用 in。誘答拆解：on 是接觸表面（放在盒子上）；at 是某一點；for 表目的或對象——只有 in 能表達「在…內部」。"}),
        v=>({s:"Attach the return label {N} the outside of the package.",
             c:"to",d:["under","among","into"],
             ex:"attach A to B＝「把 A 貼／固定到 B 上」，是固定搭配。誘答拆解：under（在下方）、among（在三者以上之間）、into（進入內部）都與「貼上」的方向不符。"}) ],
      [ v=>({s:"We apologize again for the {N}.",
             c:"inconvenience",d:["inconvenient","inconveniently","conveniently"],
             ex:"冠詞 the 後面要接「名詞」：apologize for the inconvenience（為造成的不便致歉）是客服信固定收尾。誘答拆解：inconvenient 是形容詞、inconveniently／conveniently 是副詞，都不能接在 the 後面當受詞。"}),
        v=>({s:"Thank you for your {N} while we process your request.",
             c:"patience",d:["patient","patiently","impatient"],
             ex:"所有格 your 後面要接「名詞」：your patience（您的耐心）。誘答拆解：patient 當名詞時是「病人」（語意不通），當形容詞不能接在 your 後；patiently 是副詞；impatient 是形容詞且語意相反。"}) ]
    ]},

  /* ---------- TOEIC ⑥ 新品發表 (lv2) ---------- */
  { kind:"toeic", cat:"biz", lv:2,
    title:v=>"新品快報："+v.prodZh,
    lex:[
      {prod:"ultrabook",prodZh:"輕薄筆電",time:"last week",year:"2023",adjB:"light",adjC:"lighter"},
      {prod:"smartwatch",prodZh:"智慧手錶",time:"last month",year:"2022",adjB:"thin",adjC:"thinner"},
      {prod:"tablet",prodZh:"平板電腦",time:"on Monday",year:"2024",adjB:"fast",adjC:"faster"},
      {prod:"e-reader",prodZh:"電子書閱讀器",time:"yesterday",year:"2023",adjB:"small",adjC:"smaller"},
      {prod:"camera",prodZh:"相機",time:"last Friday",year:"2022",adjB:"tough",adjC:"tougher"},
      {prod:"projector",prodZh:"投影機",time:"two weeks ago",year:"2024",adjB:"quiet",adjC:"quieter"}
    ],
    intro:()=>"To: All Sales Staff",
    outro:()=>"Marketing Department",
    slots:[
      [ v=>({s:`Our new ${v.prod} {N} at the trade show ${v.time}.`,
             c:"was unveiled",d:["has been unveiled","unveils","is unveiling"],
             ex:`「${v.time}」是明確過去時間，產品是「被發表」的對象，用過去式被動 was unveiled。誘答拆解：has been unveiled（完成式）不能與明確過去時間並用；unveils／is unveiling 是主動——產品不會自己發表自己。`}),
        v=>({s:`The design team {N} on this model since ${v.year}.`,
             c:"has been working",d:["works","is working","worked"],
             ex:`since + 起點（${v.year}）表「從過去持續到現在」，強調持續的過程用現在完成進行式 has been working。誘答拆解：works（習慣）、is working（只講此刻）都接不住 since；worked 單獨過去式表示已結束，與 since 矛盾。`}) ],
      [ v=>({s:`It is 20 percent {N} than the previous model.`,
             c:v.adjC,d:[v.adjB,"most "+v.adjB,"more "+v.adjC],
             ex:`句中有 than，要用比較級 ${v.adjC}；百分比放在比較級前表差距。誘答拆解：${v.adjB} 是原級；most ${v.adjB} 是最高級用法錯置；more ${v.adjC} 是「more + -er」的雙重比較，絕對錯誤。`}),
        v=>({s:"Early reviewers say it is the {N} product in its class.",
             c:"most reliable",d:["more reliable","reliable","reliably"],
             ex:"the + 最高級 + in 範圍＝「同級中最…的」：the most reliable。誘答拆解：more reliable 是比較級（需要 than）；reliable 原級前不加 the 表「最」；reliably 是副詞，不能修飾名詞 product。"}) ],
      [ v=>({s:"{N}, the battery lasts up to two days on a single charge.",
             c:"Moreover",d:["However","Otherwise","Instead"],
             ex:"前句稱讚產品、後句繼續補充另一優點，語意「遞進」用 Moreover（而且）。誘答拆解：However 表轉折（前後對立）；Otherwise 表「否則」；Instead 表「取而代之」——語意方向全部不符。"}),
        v=>({s:"The price, {N}, will stay the same as last year's model.",
             c:"however",d:["because","so","although"],
             ex:"前面講規格升級、這句講價格不變，語意轉折；however 是副詞，可作插入語放在句中（前後加逗號）。誘答拆解：because／although 是連接詞，要引導子句，不能當插入語；so 也是連接詞且表結果。"}) ],
      [ v=>({s:"Sales staff {N} complete the training course before selling the new model.",
             c:"must",d:["may","could","would"],
             ex:"公司規定＝強制義務，用 must（必須）。誘答拆解：may／could 表「可能、可以」，把規定弱化成選擇；would 表過去習慣或假設——都無法表達「不做不行」的強制性。"}),
        v=>({s:"Please contact the product team if you {N} more information.",
             c:"need",d:["needed","will need","would need"],
             ex:"第一類條件句：if 子句用現在式 need 表未來可能。誘答拆解：needed 過去式時態不符；if 子句不放 will（will need ✗）；would need 是與現在相反的假設，但「需要更多資訊」是真實可能發生的情況。"}) ]
    ]},

  /* ---------- TOEIC ⑦ 辦公室政策 (lv3) ---------- */
  { kind:"toeic", cat:"biz", lv:3,
    title:v=>"辦公室公告："+v.topicZh,
    lex:[
      {topicZh:"節能措施",it:"IT desk",person:"Ms. Chen"},
      {topicZh:"訪客規範",it:"help desk",person:"Mr. Novak"},
      {topicZh:"會議室使用",it:"IT desk",person:"Ms. Alvarez"},
      {topicZh:"安全守則",it:"support desk",person:"Mr. Kim"},
      {topicZh:"設備報修",it:"IT desk",person:"Ms. Dubois"},
      {topicZh:"噪音管理",it:"service desk",person:"Mr. Okafor"}
    ],
    intro:()=>"Notice to All Employees:",
    outro:()=>"General Affairs",
    slots:[
      [ v=>({s:"All visitors {N} sign in at the front desk before entering the office area.",
             c:"must",d:["might","would","could"],
             ex:"安全規定＝強制要求，用 must。誘答拆解：might／could 表「或許可以」，會把強制規定變成可有可無；would 用於假設或過去習慣——公告的語氣必須是不容商量的 must。"}),
        v=>({s:"Each of the meeting rooms {N} a new booking system installed.",
             c:"has",d:["have","are","were"],
             ex:"each of + 複數名詞，主詞是 each（單數），動詞用 has。這是主謂一致的经典陷阱——of 後面的複數名詞是干擾項。誘答拆解：have／are／were 都是複數動詞，被 rooms 誤導就會選錯。"}) ],
      [ v=>({s:"Please consider {N} the stairs instead of the elevator during peak hours.",
             c:"taking",d:["to take","take","took"],
             ex:"consider 屬於「只接動名詞」的動詞：consider + V-ing（考慮做…）。誘答拆解：to take 不定詞不能接在 consider 後（✗ consider to do）；take／took 缺乏正確的非謂語形式。同類動詞：enjoy、finish、avoid、suggest。"}),
        v=>({s:"We recommend {N} large files before sending them by email.",
             c:"compressing",d:["to compress","compress","compressed"],
             ex:"recommend 後面接動名詞 V-ing：recommend compressing（建議壓縮）。誘答拆解：recommend to V 是常見誤用；compress 原形、compressed 過去分詞都不能直接當受詞。同類：suggest、consider、avoid。"}) ],
      [ v=>({s:"Turn off the lights when you leave; {N}, energy costs will keep rising.",
             c:"otherwise",d:["moreover","therefore","however"],
             ex:"「關燈，否則電費會一直漲」——前句是要求、後句是不照做的後果，用 otherwise（否則）。誘答拆解：moreover 遞進、therefore 因果、however 轉折，都無法表達「若不遵守就會…」的警告語意。"}),
        v=>({s:"The number of complaints about noise {N} dropped since the new policy began.",
             c:"has",d:["have","is","are"],
             ex:"主詞是 the number（單數）——「the number of + 複數名詞」動詞永遠跟 number 走；since 引導的完成式再確認用 has。誘答拆解：have 被 complaints 誤導；is／are 後面不能直接接 dropped 構成完成式。"}) ],
      [ v=>({s:`Employees {N} laptops need repairs should contact the ${v.it}.`,
             c:"whose",d:["who","which","whom"],
             ex:"空格後接名詞 laptops（＝「他們的」筆電），表所有關係用 whose。誘答拆解：who 當主詞後面要接動詞而非名詞；which 指物且無所有格功能；whom 是受格。"}),
        v=>({s:"{N}",
             c:"Thank you for helping us keep the office safe and comfortable.",d:off(OFF_BIZ,5),
             ex:"整句插入題：政策公告的收尾應感謝員工配合、呼應「維護辦公環境」的主旨。其餘選項與公告內容毫無關聯，屬於離題誘答。"}) ]
    ]},

  /* ---------- TOEIC ⑧ 活動邀請 (lv1) ---------- */
  { kind:"toeic", cat:"biz", lv:1,
    title:v=>"活動邀請："+v.eventZh,
    lex:[
      {event:"annual banquet",eventZh:"年度晚宴",hall:"Grand Hall",day:"Friday, May 10",day2:"Monday",amt:"200"},
      {event:"awards night",eventZh:"頒獎之夜",hall:"Crystal Ballroom",day:"Saturday, June 21",day2:"Wednesday",amt:"150"},
      {event:"year-end party",eventZh:"尾牙派對",hall:"Sunset Terrace",day:"Friday, December 19",day2:"Friday",amt:"300"},
      {event:"charity dinner",eventZh:"慈善晚宴",hall:"Garden Pavilion",day:"Saturday, April 12",day2:"Tuesday",amt:"180"},
      {event:"welcome reception",eventZh:"迎新酒會",hall:"Sky Lounge",day:"Thursday, September 4",day2:"Monday",amt:"120"},
      {event:"anniversary gala",eventZh:"週年慶典",hall:"Royal Hall",day:"Saturday, October 18",day2:"Thursday",amt:"250"}
    ],
    intro:()=>"Dear Colleagues,",
    outro:()=>"Event Committee",
    slots:[
      [ v=>({s:`Our ${v.event} {N} at the ${v.hall} on ${v.day}.`,
             c:"will be held",d:["will hold","is holding","holds"],
             ex:"活動是「被舉辦」的對象，未來的活動用未來式被動 will be held。誘答拆解：will hold／is holding／holds 都是主動語態——活動不會自己舉辦自己，被動必須有 be + p.p.。"}),
        v=>({s:`More than ${v.amt} guests {N} to attend this year.`,
             c:"are expected",d:["expect","are expecting","expected"],
             ex:"be expected to V＝「預計、被期待」，賓客是「被預期」出席的對象，用被動 are expected。誘答拆解：expect／are expecting 是主動（變成賓客在期待別人）；expected 缺 be 動詞。"}) ],
      [ v=>({s:"The dinner will begin {N} 6:30 p.m. sharp.",
             c:"at",d:["in","on","by"],
             ex:"精確時刻（6:30 p.m.）用 at；sharp＝「整點準時」。誘答拆解：in 接大範圍時間（月、年）；on 接日期或星期；by 是「在…之前完成」的期限，與「開始於」不符。"}),
        v=>({s:"Please arrive {N} 15 minutes before the opening speech.",
             c:"at least",d:["at most","at first","at last"],
             ex:"at least＝「至少」（提早至少 15 分鐘）。誘答拆解：at most 是「至多」（語意剛好相反）；at first 是「起初」；at last 是「終於」——三者都與「提前量」無關。"}) ],
      [ v=>({s:`The ${v.hall}, {N} was rebuilt last year, can hold 500 people.`,
             c:"which",d:["that","who","where"],
             ex:"逗號後的「非限定」關係子句補充說明場地（物），只能用 which——非限定子句不可用 that，這是鐵律。誘答拆解：who 指人；where 是關係副詞，只能接完整句子，但這裡子句缺主詞。"}),
        v=>({s:"Guests {N} plan to bring a partner should let us know by "+v.day2+".",
             c:"who",d:["whose","which","whom"],
             ex:"先行詞 Guests 指人、在子句中當主詞（___ plan to…），用主格 who。誘答拆解：whose 後面要接名詞；which 指物；whom 是受格不能當主詞。"}) ],
      [ v=>({s:"{N}",
             c:"Please reply to this email to reserve your seat.",d:off(OFF_BIZ,6),
             ex:"整句插入題：邀請函的行動呼籲（call to action）＝請回信訂位，與整封信的目的一致。其他選項與活動邀請完全無關。"}),
        v=>({s:"{N}",
             c:"We hope to celebrate this special evening with you.",d:off(OFF_BIZ,7),
             ex:"整句插入題：邀請函的溫暖收尾＝期待與您共度。判斷方法：把每個選項放回文章末尾讀一次，只有這句讓文意通順。"}) ]
    ]},

  /* ---------- TOEIC ⑨ 差旅報帳規定 (lv3) ---------- */
  { kind:"toeic", cat:"biz", lv:3,
    title:v=>"報帳規定：上限 $"+v.amt,
    lex:[
      {amt:"100"},{amt:"80"},{amt:"150"},{amt:"200"},{amt:"120"},{amt:"60"}
    ],
    intro:()=>"Subject: Travel Expense Rules",
    outro:()=>"Finance Department",
    slots:[
      [ v=>({s:"Receipts {N} within two weeks of your return.",
             c:"must be submitted",d:["must submit","submitted","must be submitting"],
             ex:"收據是「被繳交」的對象，情態助動詞的被動＝must be + p.p.：must be submitted。誘答拆解：must submit 是主動（收據不會自己繳交）；submitted 缺助動詞與 be；must be submitting 是進行式，規定不用進行式。"}),
        v=>({s:`Any expense over $${v.amt} {N} by a manager first.`,
             c:"has to be approved",d:["has to approve","approves","is approving"],
             ex:"費用是「被核准」的對象：has to be + p.p.＝「必須被…」。誘答拆解：has to approve／approves／is approving 都是主動——expense 是被審核的對象，不是審核者；by a manager 更提示了被動結構。"}) ],
      [ v=>({s:"Flights were delayed several times last month {N} the storm season.",
             c:"because of",d:["because","although","so that"],
             ex:"後面接名詞片語 the storm season，用介系詞 because of。誘答拆解：because 接「主詞＋動詞」子句；although 讓步且需接子句；so that 表目的。「because of + 名詞／because + 子句」是必考區辨。"}),
        v=>({s:"{N} costs keep rising, the travel budget will stay the same this year.",
             c:"Although",d:["Because","Unless","So"],
             ex:"「成本上漲」與「預算不變」語意對立，用讓步連接詞 Although（雖然）。誘答拆解：Because 表因果（漲價所以預算不變？矛盾）；Unless 是「除非」；So 是「所以」且不能放句首連接這種結構。"}) ],
      [ v=>({s:"Choose the most {N} option when booking hotels.",
             c:"economical",d:["economically","economy","economize"],
             ex:"the most ___ option：修飾名詞 option 用形容詞 economical（經濟實惠的）。誘答拆解：economically 是副詞；economy 是名詞（經濟）；economize 是動詞（節約）——詞性全錯。多益詞性題：名詞前面找形容詞。"}),
        v=>({s:"Complete the online form {N} to avoid delays in payment.",
             c:"promptly",d:["prompt","promptness","prompted"],
             ex:"修飾動詞 complete（如何填寫）用副詞 promptly（迅速地）。誘答拆解：prompt 是形容詞；promptness 是名詞；prompted 是過去分詞——修飾動詞只能用副詞，這是 Part 5/6 最高頻的詞性考點。"}) ],
      [ v=>({s:"Employees {N} ignore these rules may not be reimbursed.",
             c:"who",d:["whose","which","whom"],
             ex:"先行詞 Employees 指人、當子句主詞，用 who。誘答拆解：whose 接名詞表所有；which 指物；whom 受格。另外 may not be reimbursed（可能無法獲得核銷）是被動，證明本題只考關代。"}),
        v=>({s:"Travelers {N} keep their boarding passes as proof of the trip.",
             c:"must",d:["might","would","could"],
             ex:"報帳規定＝義務，用 must（必須保留登機證）。誘答拆解：might／could 表可能性，會把規定弱化；would 用於假設或過去習慣——公告規範一律用 must / have to。"}) ]
    ]},

  /* ---------- TOEIC ⑩ 滿意度調查 (lv1) ---------- */
  { kind:"toeic", cat:"biz", lv:1,
    title:v=>"滿意度調查："+v.placeZh,
    lex:[
      {place:"hotel",placeZh:"飯店",time:"last week"},
      {place:"restaurant",placeZh:"餐廳",time:"last weekend"},
      {place:"resort",placeZh:"度假村",time:"last month"},
      {place:"café",placeZh:"咖啡館",time:"yesterday"},
      {place:"spa",placeZh:"水療中心",time:"on Sunday"},
      {place:"inn",placeZh:"旅店",time:"last Friday"}
    ],
    intro:v=>`Dear Guest,\n\nThank you for visiting our ${v.place} ${v.time}.`,
    outro:()=>"Guest Relations Team",
    slots:[
      [ v=>({s:`We hope you enjoyed {N} at our ${v.place}.`,
             c:"staying",d:["to stay","stay","stayed"],
             ex:"enjoy 屬於「只接動名詞」的動詞：enjoy + V-ing。誘答拆解：enjoy to V 是最經典的錯誤搭配；stay 原形、stayed 過去式都不能當 enjoy 的受詞。同類動詞：finish、avoid、mind、practice。"}),
        v=>({s:"We were pleased {N} you as our guest.",
             c:"to welcome",d:["welcoming","welcome","welcomed"],
             ex:"be pleased to V＝「很高興做…」，固定接不定詞。誘答拆解：pleased 後面接 V-ing 不是標準搭配；welcome 原形、welcomed 過去分詞都無法接在 pleased 後構成正確句型。"}) ],
      [ v=>({s:"Could you take two minutes {N} our short survey?",
             c:"to complete",d:["completing","complete","completed"],
             ex:"take + 時間 + to V＝「花時間做…」：take two minutes to complete。誘答拆解：completing 用於 spend + 時間 + V-ing 的句型（主詞是人）；complete 原形缺 to；completed 是過去分詞。spend 配 V-ing、take 配 to V，成對記憶。"}),
        v=>({s:"We would appreciate it if you {N} share your thoughts with us.",
             c:"could",d:["will","must","may"],
             ex:"would appreciate it if + S + could/would…＝「如果您能…我們將感激」，是最客氣的商用請求句型，if 子句配過去式助動詞 could。誘答拆解：will／must／may 現在式助動詞與 would appreciate 的委婉語氣不一致。"}) ],
      [ v=>({s:"Your answers will help us serve you even {N} in the future.",
             c:"better",d:["good","best","well"],
             ex:"even 加強「比較級」：serve you even better（服務得更好）。誘答拆解：good 是形容詞原級；well 是副詞原級——兩者都不能被 even 加強比較；best 是最高級，前面應有 the 且語境是「與現在相比」而非「最」。"}),
        v=>({s:"{N}, everyone who replies will get a discount coupon.",
             c:"Moreover",d:["However","Otherwise","Instead"],
             ex:"前句請求填問卷、後句加碼送折價券，語意「遞進」用 Moreover（而且）。誘答拆解：However 轉折、Otherwise 否則、Instead 取而代之——方向全不符。判斷連接副詞先問：前後句是順著說還是反著說？"}) ],
      [ v=>({s:"{N}",
             c:"Simply click the link below to begin the survey.",d:off(OFF_BIZ,2),
             ex:"整句插入題：問卷邀請信必須告訴收件人「怎麼開始」——點擊下方連結。這是行動呼籲句，其餘選項與問卷情境完全無關。"}),
        v=>({s:"{N}",
             c:"Thank you in advance for your time and support.",d:off(OFF_BIZ,3),
             ex:"整句插入題：先行致謝（thank you in advance）是請求協助類信件的標準收尾。其他選項放在信末會顯得莫名其妙、破壞文意。"}) ]
    ]},

  /* ---------- CEEC ① 社團招生 (lv1) ---------- */
  { kind:"ceec", cat:"word", lv:1,
    title:v=>"社團招生："+v.clubZh,
    lex:[
      {club:"music club",clubZh:"音樂社",room:"201",day:"Friday"},
      {club:"photography club",clubZh:"攝影社",room:"305",day:"Thursday"},
      {club:"drama club",clubZh:"戲劇社",room:"102",day:"Wednesday"},
      {club:"science club",clubZh:"科學社",room:"408",day:"Monday"},
      {club:"hiking club",clubZh:"登山社",room:"210",day:"Tuesday"},
      {club:"art club",clubZh:"美術社",room:"116",day:"Friday"}
    ],
    intro:v=>`Looking for something fun after class? Join the ${v.club}!`,
    outro:()=>"",
    slots:[
      [ v=>({s:"Our club meets every Wednesday, and new members {N} always welcome.",
             c:"are",d:["is","be","been"],
             ex:"主詞 new members 是複數，be 動詞用 are。誘答拆解：is 是單數；be 原形不能單獨當述語動詞；been 是過去分詞，必須跟在 have/has 之後。"}),
        v=>({s:"Joining a club is one of the {N} ways to make friends in high school.",
             c:"best",d:["better","good","well"],
             ex:"one of the + 最高級 + 複數名詞＝「最…的之一」。誘答拆解：better 是比較級（需要 than）；good 原級無法搭配 the 表「最」；well 是副詞不能修飾名詞 ways。"}) ],
      [ v=>({s:"You don't need {N} experience—just bring your interest.",
             c:"much",d:["many","a few","few"],
             ex:"experience（經驗）是不可數名詞，「多」用 much。誘答拆解：many、a few、few 都只能修飾可數複數名詞。不可數常客：advice、information、furniture、homework。"}),
        v=>({s:"There are {N} different activities to choose from each month.",
             c:"many",d:["much","a little","little"],
             ex:"activities 是可數複數名詞，「多」用 many。誘答拆解：much、a little、little 都只能修飾不可數名詞——先判斷名詞可不可數，再選數量詞。"}) ],
      [ v=>({s:"Students {N} love music can also join our band section.",
             c:"who",d:["whose","which","whom"],
             ex:"先行詞 Students 指人、在子句中當主詞，用 who。誘答拆解：whose 是所有格（後接名詞）；which 指物；whom 是受格，不能接動詞 love 當主詞。"}),
        v=>({s:"The club room, {N} is next to the library, is open every afternoon.",
             c:"which",d:["that","who","where"],
             ex:"逗號後的非限定子句補充說明 club room（物），用 which；非限定子句不能用 that。誘答拆解：who 指人；where 後面要接「完整句子」，但這裡缺主詞——缺什麼補什麼，缺主詞用關代。"}) ],
      [ v=>({s:"If you sign up this week, you {N} a free club T-shirt.",
             c:"will get",d:["got","would get","had gotten"],
             ex:"第一類條件句：If + 現在式（sign up），主句用 will + V（will get）。誘答拆解：got 過去式時間不符；would get 是第二類（與現在相反）的假設；had gotten 屬於第三類（與過去相反）——本句是真實可能發生的未來。"}),
        v=>({s:"{N}",
             c:`Come to Room ${v.room} on ${v.day} to learn more!`,d:off(OFF_GEN,0),
             ex:"整句插入題：招生海報的收尾必須告訴讀者「下一步怎麼做」——哪天到哪間教室了解詳情，這是行動呼籲句。其他選項（餐廳油漆、親戚住處、水的沸點）與社團招生毫無關聯，屬於離題誘答。"}) ]
    ]},

  /* ---------- CEEC ② 週末出遊 (lv1) ---------- */
  { kind:"ceec", cat:"tense", lv:1,
    title:v=>"週末出遊："+v.placeZh,
    lex:[
      {place:"the mountains",placeZh:"山區",day:"Saturday"},
      {place:"Kenting",placeZh:"墾丁",day:"Sunday"},
      {place:"a hot spring town",placeZh:"溫泉小鎮",day:"Saturday"},
      {place:"the north coast",placeZh:"北海岸",day:"Sunday"},
      {place:"Sun Moon Lake",placeZh:"日月潭",day:"Saturday"},
      {place:"an old street",placeZh:"老街",day:"Sunday"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:`Last ${v.day}, my family {N} to ${v.place} for a short trip.`,
             c:"went",d:["go","gone","have gone"],
             ex:`Last ${v.day} 是明確的過去時間，用過去簡單式；go 的過去式是不規則的 went。誘答拆解：go 是現在式；gone 是過去分詞，必須跟在 have/has/had 後；have gone（完成式）不能與明確過去時間並用。`}),
        v=>({s:"We {N} early in the morning so that we could avoid the heavy traffic.",
             c:"set off",d:["set up","set down","set in"],
             ex:"set off＝「出發」。誘答拆解：set up 是「設立、架設」；set down 是「放下、記下」；set in 是「（壞天氣等）開始」——動詞片語的介副詞決定意思，必須整組記。"}) ],
      [ v=>({s:"While we {N} lunch by the river, it suddenly started to rain.",
             c:"were having",d:["had","have","are having"],
             ex:"while + 過去進行式＝正在進行的「背景動作」，突發事件（started to rain）打斷它：were having lunch。誘答拆解：had 單獨過去式失去「正在進行」的畫面感（while 強烈暗示進行式）；have／are having 是現在式，與過去的故事矛盾。"}),
        v=>({s:"We {N} just finished eating when the sun came out again.",
             c:"had",d:["have","has","are"],
             ex:"兩件過去的事：先「吃完」、後「太陽出來」——較早的動作用過去完成式 had + p.p.（had just finished）。誘答拆解：have/has finished 是現在完成式（連結到現在，但這是過去的故事）；are 無法構成完成式。"}) ],
      [ v=>({s:"The scenery there was much {N} than we had expected.",
             c:"more beautiful",d:["beautiful","most beautiful","beautifully"],
             ex:"句中有 than，用比較級；beautiful 是多音節形容詞，比較級加 more；much 用來加強比較級（美得多）。誘答拆解：beautiful 原級不能配 than；most beautiful 是最高級；beautifully 是副詞，不能描述主詞 scenery。"}),
        v=>({s:"It was the {N} weekend we had spent together in years.",
             c:"happiest",d:["happier","happy","happily"],
             ex:"the + 最高級＝「最…的」：the happiest weekend。happy 的最高級：y 變 i 加 -est。誘答拆解：happier 是比較級（需 than）；happy 原級前的 the 無法表「最」；happily 是副詞不能修飾名詞 weekend。"}) ],
      [ v=>({s:"{N} we were tired at the end of the day, everyone agreed it was a wonderful trip.",
             c:"Although",d:["Because","Unless","So"],
             ex:"「很累」與「很棒」語意對立，用讓步連接詞 Although（雖然）。誘答拆解：Because 表因果（因為累所以很棒？不通）；Unless 是「除非」；So 表結果且不能這樣放句首接兩個子句。注意：用了 Although 就不能再加 but。"}),
        v=>({s:"We didn't get home {N} nine o'clock that night.",
             c:"until",d:["since","by","from"],
             ex:"not … until＝「直到…才…」：直到九點才到家。誘答拆解：since 是「自從」（配完成式）；by 是「在…之前」（deadline，與 not 搭配語意矛盾）；from 是起點。not…until 是學測翻譯與選擇的雙料常客。"}) ]
    ]},

  /* ---------- CEEC ③ 健康習慣 (lv2) ---------- */
  { kind:"ceec", cat:"word", lv:2,
    title:v=>"健康專欄："+v.topicZh,
    lex:[
      {topicZh:"早餐與精神",min:"thirty"},
      {topicZh:"睡眠品質",min:"twenty"},
      {topicZh:"運動習慣",min:"forty"},
      {topicZh:"3C 使用",min:"sixty"},
      {topicZh:"飲食均衡",min:"thirty"},
      {topicZh:"壓力管理",min:"fifteen"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:"Teenagers who skip breakfast {N} to feel tired before noon.",
             c:"tend",d:["tends","tending","tended"],
             ex:"主詞是 Teenagers（複數）——who skip breakfast 只是修飾語，動詞要跟主詞一致用原形 tend。誘答拆解：tends 是第三人稱單數（被子句內的 breakfast 誤導就會選錯）；tending／tended 無法當現在式述語。"}),
        v=>({s:"Doctors say that drinking enough water {N} the body work properly.",
             c:"helps",d:["help","helping","helped"],
             ex:"主詞是動名詞片語 drinking enough water——動名詞當主詞視為「單數」，動詞用 helps；help + O + 原形（work）。誘答拆解：help 複數形被 Doctors 誤導；helping／helped 不能當 that 子句的述語動詞。"}) ],
      [ v=>({s:"{N}, staying up late makes it even harder to focus in class.",
             c:"Moreover",d:["However","Otherwise","Instead"],
             ex:"前後句都在講「壞習慣傷身」，語意遞進用 Moreover（而且）。誘答拆解：However 需要前後對立；Otherwise 是「否則」；Instead 是「取而代之」。先讀懂前後句方向一致，再選遞進詞。"}),
        v=>({s:"Fast food tastes good; {N}, eating too much of it harms your health.",
             c:"however",d:["moreover","therefore","instead"],
             ex:"「好吃」與「傷身」語意轉折，用 however；注意標準格式：分號＋however＋逗號。誘答拆解：moreover 遞進、therefore 因果、instead 替代——只有 however 能表達前後對立。"}) ],
      [ v=>({s:`Experts suggest {N} for at least ${v.min} minutes a day.`,
             c:"exercising",d:["to exercise","exercise","exercised"],
             ex:"suggest 屬於「只接動名詞」的動詞：suggest + V-ing。誘答拆解：suggest to V 是經典錯誤；exercise 原形、exercised 過去式都不能當 suggest 的受詞。同類動詞：enjoy、finish、avoid、consider、recommend。"}),
        v=>({s:"Try to avoid {N} your phone right before bed.",
             c:"using",d:["to use","use","used"],
             ex:"avoid 只接動名詞：avoid + V-ing（避免做…）。誘答拆解：avoid to V 不存在；use 原形、used 過去式都不是正確的非謂語形式。記法：avoid（避開）的事通常「已在發生或反覆發生」，所以配 V-ing。"}) ],
      [ v=>({s:"If you build these habits now, you {N} the benefits for years to come.",
             c:"will enjoy",d:["enjoyed","would enjoy","had enjoyed"],
             ex:"第一類條件句：If + 現在式（build），主句用 will + V。誘答拆解：enjoyed 過去式時態錯位；would enjoy 是第二類假設（暗示不可能，但養成習慣是可能的）；had enjoyed 屬於過去完成式。"}),
        v=>({s:"The earlier you start, {N} it becomes to stay healthy.",
             c:"the easier",d:["easier","the easiest","easily"],
             ex:"「越…越…」句型：The + 比較級…, the + 比較級…——兩個 the 都不能省：the earlier…, the easier…。誘答拆解：easier 少了 the；the easiest 是最高級；easily 是副詞且不符句型。"}) ]
    ]},

  /* ---------- CEEC ④ 環保議題 (lv2) ---------- */
  { kind:"ceec", cat:"voice", lv:2,
    title:v=>"環境專題："+v.topicZh,
    lex:[
      {topicZh:"海洋塑膠",yr:"2050"},
      {topicZh:"一次性餐具",yr:"2040"},
      {topicZh:"塑膠微粒",yr:"2060"},
      {topicZh:"海灘垃圾",yr:"2045"},
      {topicZh:"河川污染",yr:"2055"},
      {topicZh:"塑膠袋問題",yr:"2050"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:"Plastic waste {N} into the ocean every year in huge amounts.",
             c:"is dumped",d:["dumps","is dumping","dumped"],
             ex:"塑膠垃圾是「被倒入」海洋的對象，every year 表常態，用現在式被動 is dumped。誘答拆解：dumps／is dumping 是主動（垃圾不會自己倒自己）；dumped 缺 be 動詞，不构成被動語態。"}),
        v=>({s:"Millions of bottles {N} away after only one use.",
             c:"are thrown",d:["throw","are throwing","thrown"],
             ex:"瓶子是「被丟棄」的對象，主詞複數用 are + p.p.：are thrown away。誘答拆解：throw／are throwing 是主動；thrown 單獨的過去分詞缺 be 動詞。搭配 throw away（丟棄），被動時整組保留。"}) ],
      [ v=>({s:"Sea animals often mistake plastic bags {N} food.",
             c:"for",d:["as","to","with"],
             ex:"mistake A for B＝「把 A 誤認為 B」，是固定搭配。誘答拆解：as 是最強的誘答（regard A as B 才用 as）；to、with 皆不成搭配。固定搭配題靠平時整組記憶：mistake…for、regard…as、prevent…from。"}),
        v=>({s:"The problem {N} much worse since cheap plastic became common.",
             c:"has grown",d:["grew","grows","is growing"],
             ex:"since + 過去起點＝「從那時到現在」，主句用現在完成式 has grown。誘答拆解：grew 單獨過去式接不住 since 的「持續到現在」；grows 現在習慣、is growing 只講此刻，都無法涵蓋整段時間。"}) ],
      [ v=>({s:"{N}, small actions like bringing your own bag can make a real difference.",
             c:"However",d:["Therefore","Moreover","Instead"],
             ex:"前文描述問題嚴重、這句轉向「個人仍有辦法」，語意轉折用 However。誘答拆解：Therefore 因果、Moreover 遞進（方向相同才能用）、Instead 替代——只有 However 能完成「問題雖大，但…」的轉彎。"}),
        v=>({s:"Everyone, {N} governments and companies, has a role to play.",
             c:"including",d:["include","included","inclusion"],
             ex:"including + 名詞＝「包括…在內」，插入語形式固定用 V-ing。誘答拆解：include 是動詞原形（句中已有述語 has）；included 要用在名詞之後（governments included）；inclusion 是名詞，無法引導插入語。"}) ],
      [ v=>({s:"We {N} act now, or the damage will be permanent.",
             c:"must",d:["might","would","could"],
             ex:"「現在必須行動，否則…」——強烈的必要性用 must；後面的 or（否則）強化了急迫語氣。誘答拆解：might／could 只是「或許可以」；would 用於假設——都撐不起「非做不可」的語意。"}),
        v=>({s:`Scientists warn that the ocean {N} more plastic than fish by ${v.yr} if nothing changes.`,
             c:"could contain",d:["containing","contain","to contain"],
             ex:"that 子句需要完整的述語動詞：could contain（可能含有）＝情態助動詞＋原形。誘答拆解：containing／to contain 都是非謂語形式，不能單獨當述語；contain 缺了表推測的助動詞，且與第三人稱單數 the ocean 不一致。"}) ]
    ]},

  /* ---------- CEEC ⑤ 克服困難 (lv3) ---------- */
  { kind:"ceec", cat:"verb", lv:3,
    title:v=>"成長故事："+v.contestZh,
    lex:[
      {contest:"school speech contest",contestZh:"校內演講比賽"},
      {contest:"English recitation contest",contestZh:"英語朗讀比賽"},
      {contest:"debate final",contestZh:"辯論決賽"},
      {contest:"talent show",contestZh:"才藝表演"},
      {contest:"drama festival",contestZh:"戲劇節公演"},
      {contest:"city singing competition",contestZh:"市級歌唱比賽"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:"When I first tried speaking on stage, I was too nervous {N} my notes.",
             c:"to read",d:["reading","read","for reading"],
             ex:"too + 形容詞 + to V＝「太…而無法…」：緊張到讀不了稿子。注意句中沒有 not，否定意味藏在 too…to 裡。誘答拆解：reading／read 都不符合 too…to 的固定結構；for reading 的介系詞用法在此不成立。"}),
        v=>({s:"My voice was {N} quiet that people in the back could not hear me.",
             c:"so",d:["such","very","too"],
             ex:"so + 形容詞 + that 子句＝「如此…以致於…」。誘答拆解：such 後面要接（a）＋形容詞＋名詞（such a quiet voice that…）；very 不能與 that 子句連動；too 的固定搭配是 to V 不是 that 子句。"}) ],
      [ v=>({s:"Instead of {N} up, I practiced in front of a mirror every night.",
             c:"giving",d:["give","to give","gave"],
             ex:"instead of 是介系詞片語，後面的動詞一律用 V-ing：instead of giving up（不放棄，反而…）。誘答拆解：give 原形、gave 過去式不能接在介系詞後；to give 是不定詞，介系詞後不接 to V。"}),
        v=>({s:"My teacher encouraged me {N} trying even after I failed twice.",
             c:"to keep",d:["keeping","kept","keeps"],
             ex:"encourage + 受詞 + to V＝「鼓勵某人去做」：encouraged me to keep trying。誘答拆解：keeping／kept／keeps 都不能接在受詞 me 後構成這個句型。同類動詞：advise、allow、ask、tell + O + to V。"}) ],
      [ v=>({s:`Six months later, I {N} first prize in the ${v.contest}.`,
             c:"won",d:["win","have won","had won"],
             ex:"Six months later 在敘事中是明確的過去時間點，用過去簡單式 won。誘答拆解：win 現在式；have won 完成式與明確過去時間衝突；had won 過去完成式需要「更晚的過去事件」作參照，本句沒有。"}),
        v=>({s:"By the end of that year, I {N} in front of hundreds of people.",
             c:"had spoken",d:["speak","have spoken","was speaking"],
             ex:"by the end of that year（到那年年底前）＝過去的期限，期限前完成的動作用過去完成式 had spoken。誘答拆解：speak 現在式；have spoken 連到「現在」但故事在過去；was speaking 只是進行中，缺「已完成」的意味。"}) ],
      [ v=>({s:"That experience taught me that confidence {N} through daily practice.",
             c:"is built",d:["builds","building","is building"],
             ex:"信心是「被建立」的對象，表普遍真理用現在式被動 is built。誘答拆解：builds 是主動（信心不會自己建立自己）；building 缺 be 動詞；is building 主動進行式，同樣把 confidence 當成了執行者。"}),
        v=>({s:"Looking back, I am glad that I {N} away from the challenge.",
             c:"didn't run",d:["don't run","haven't run","won't run"],
             ex:"回顧「當時」沒有逃避——過去的否定用 didn't + 原形。誘答拆解：don't run 是現在習慣；haven't run 完成式連到現在（但事件已在過去定格）；won't run 是未來。敘事回顧的時間錨點在過去。"}) ]
    ]},

  /* ---------- CEEC ⑥ 家庭寵物 (lv1) ---------- */
  { kind:"ceec", cat:"clause", lv:1,
    title:v=>"我家的"+v.petZh+"："+v.name,
    lex:[
      {pet:"dog",petZh:"狗",name:"Lucky"},
      {pet:"cat",petZh:"貓",name:"Momo"},
      {pet:"dog",petZh:"狗",name:"Happy"},
      {pet:"rabbit",petZh:"兔子",name:"Snow"},
      {pet:"parrot",petZh:"鸚鵡",name:"Kiwi"},
      {pet:"cat",petZh:"貓",name:"Mimi"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:`My family has a ${v.pet} {N} name is ${v.name}.`,
             c:"whose",d:["who","which","whom"],
             ex:`空格後面直接接名詞 name（＝「牠的」名字），表所有關係用 whose——whose 人與動物皆可用。誘答拆解：who／whom 後面不能直接接名詞；which 沒有所有格功能（要說 the name of which，太拗口）。`}),
        v=>({s:`${v.name} is the cutest ${v.pet} {N} I have ever seen.`,
             c:"that",d:["who","whose","where"],
             ex:"先行詞被「最高級」修飾（the cutest…）時，關係代名詞慣用 that。誘答拆解：who 用於人；whose 是所有格；where 是關係副詞（需接完整句子，但這裡 seen 缺受詞）。最高級、序數、the only 之後都愛用 that。"}) ],
      [ v=>({s:`Taking care of ${v.name} makes me {N} responsible.`,
             c:"feel",d:["to feel","feeling","felt"],
             ex:"使役動詞 make + 受詞 + 原形動詞：makes me feel responsible。誘答拆解：make me to feel 是最經典的錯誤（make 後不加 to）；feeling／felt 都不是原形。同規則：let、have + O + 原形。"}),
        v=>({s:`My mom lets ${v.name} {N} on the sofa on weekends.`,
             c:"sleep",d:["to sleep","sleeping","slept"],
             ex:"使役動詞 let + 受詞 + 原形動詞：lets him sleep。誘答拆解：let sb to V 不存在；sleeping 是進行式或動名詞；slept 是過去式——let 後面永遠接原形，沒有例外。"}) ],
      [ v=>({s:`Last winter, ${v.name} was sick for a week, {N} made everyone in my family worried.`,
             c:"which",d:["what","that","it"],
             ex:"逗號後的 which 可以代替「前面一整件事」（生病一週這件事）當子句主詞。誘答拆解：what 不能有先行詞；that 不能用於非限定子句（逗號後）；it 是代名詞，會造成兩個句子沒有連接詞的斷句錯誤。"}),
        v=>({s:`The vet {N} took care of ${v.name} was very patient and kind.`,
             c:"who",d:["which","whose","whom"],
             ex:"先行詞 the vet（獸醫）是人、且在子句中當主詞，用 who。誘答拆解：which 指物；whose 後接名詞表所有；whom 是受格——空格後面直接接動詞 took，缺的是主詞。"}) ],
      [ v=>({s:"Now he is healthy again and {N} than ever before.",
             c:"stronger",d:["strong","strongest","more strong"],
             ex:"than 出現＝比較級：stronger than ever（比以往都健壯）。誘答拆解：strong 原級不能配 than；strongest 是最高級；more strong 犯了「單音節形容詞用 more」的錯——短的加 -er，長的用 more，二選一不能混。"}),
        v=>({s:"We hope to spend {N} more happy years with him.",
             c:"many",d:["much","a little","little"],
             ex:"years 是可數複數名詞，用 many 修飾：many more years（更多年）。誘答拆解：much、a little、little 都只能修飾不可數名詞——先問名詞可不可數，再選數量詞，這一步不能跳。"}) ]
    ]},

  /* ---------- CEEC ⑦ 旅遊文化 (lv2) ---------- */
  { kind:"ceec", cat:"compare", lv:2,
    title:v=>"旅行手記："+v.cityZh,
    lex:[
      {city:"Tainan",cityZh:"台南",dish:"beef noodles"},
      {city:"Kyoto",cityZh:"京都",dish:"matcha desserts"},
      {city:"Hoi An",cityZh:"會安",dish:"fresh spring rolls"},
      {city:"Lisbon",cityZh:"里斯本",dish:"egg tarts"},
      {city:"Chiang Mai",cityZh:"清邁",dish:"mango sticky rice"},
      {city:"Lukang",cityZh:"鹿港",dish:"oyster omelets"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:`${v.city} is one of the {N} cities I have ever visited.`,
             c:"most charming",d:["more charming","charming","charmingly"],
             ex:"one of the + 最高級 + 複數名詞：the most charming cities（最迷人的城市之一）。誘答拆解：more charming 是比較級；charming 原級無法與 the…ever 的「最」語意配合；charmingly 是副詞，不能修飾名詞。"}),
        v=>({s:"The old town is far {N} than the photos on the internet suggest.",
             c:"more beautiful",d:["beautiful","most beautiful","beautifully"],
             ex:"than 出現＝比較級：more beautiful；far 用來加強比較級（美得多），與 much 同功能。誘答拆解：beautiful 原級不能配 than；most beautiful 是最高級；beautifully 是副詞。加強比較級：much／far／a lot ✓，very ✗。"}) ],
      [ v=>({s:"People there have kept traditions {N} go back hundreds of years.",
             c:"that",d:["who","whose","where"],
             ex:"先行詞 traditions（物）且子句缺主詞，用 that（或 which）。誘答拆解：who 指人；whose 是所有格；where 需接完整句子——這裡 go back 缺主詞，所以要用關係代名詞而非關係副詞。"}),
        v=>({s:"The night market, {N} opens at six every evening, is always full of visitors.",
             c:"which",d:["that","who","where"],
             ex:"逗號後的非限定子句用 which——that 不能出現在非限定子句，這是鐵律。誘答拆解：who 指人；where 後面要接完整句子，但 opens 前缺主詞。「逗號之後見 that 直接刪」是速判口訣。"}) ],
      [ v=>({s:`Travelers can try local dishes {N} with the freshest ingredients.`,
             c:"made",d:["making","make","to make"],
             ex:"dishes (that are) made with…＝「用…做成的」料理——菜是「被做」的，用過去分詞 made 修飾名詞。誘答拆解：making 是主動（菜不會自己做菜）；make／to make 都無法直接修飾前面的名詞。分詞修飾：主動 -ing、被動 p.p.。"}),
        v=>({s:"You can hear street musicians {N} traditional songs on every corner.",
             c:"playing",d:["played","to play","plays"],
             ex:"感官動詞 hear + 受詞 + V-ing＝聽到「正在」演奏：hear musicians playing。誘答拆解：played 過去分詞表被動（樂手是主動演奏）；to play 不定詞不能接在感官動詞後；plays 是第三人稱單數動詞，不是非謂語形式。"}) ],
      [ v=>({s:"{N} the city is not big, it offers an amazing variety of food and history.",
             c:"Although",d:["Because","Unless","So"],
             ex:"「城市不大」與「內容豐富」語意對立，用讓步連接詞 Although。誘答拆解：Because 因果矛盾；Unless 是「除非」；So 表結果且位置不對。提醒：Although 和 but 一山不容二虎，只能擇一。"}),
        v=>({s:`No visit is complete {N} tasting the famous ${v.dish}.`,
             c:"without",d:["with","for","about"],
             ex:`No…without…＝「沒有…就不算…」雙重否定表「必要」：不嚐 ${v.dish} 就不算來過。誘答拆解：with 語意剛好相反；for、about 都無法構成這個句型。without 後接動名詞 tasting（介系詞+V-ing）。`}) ]
    ]},

  /* ---------- CEEC ⑧ 科技生活 (lv3) ---------- */
  { kind:"ceec", cat:"syntax", lv:3,
    title:v=>"科技評論："+v.topicZh,
    lex:[
      {topicZh:"手機與人際",age:"two"},
      {topicZh:"社群媒體",age:"three"},
      {topicZh:"線上學習",age:"five"},
      {topicZh:"短影音",age:"four"},
      {topicZh:"通訊軟體",age:"two"},
      {topicZh:"遊戲成癮",age:"six"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:"Smartphones {N} the way people communicate over the past decade.",
             c:"have changed",d:["changed","change","are changing"],
             ex:"over the past decade（過去十年來）＝從過去延續到現在的時間範圍，用現在完成式 have changed。誘答拆解：changed 單獨過去式切斷了與現在的連結；change 現在式、are changing 進行式都涵蓋不了「十年」的跨度。"}),
        v=>({s:"Never {N} so easy to reach someone on the other side of the world.",
             c:"has it been",d:["it has been","has been it","it was"],
             ex:"否定副詞 Never 放句首，主詞與助動詞必須「倒裝」：Never has it been…。誘答拆解：it has been 是未倒裝的原句序（Never 在句首時錯誤）；has been it 語序錯亂；it was 同樣未倒裝且時態不符。"}) ],
      [ v=>({s:"{N}, spending too many hours online can harm real friendships.",
             c:"However",d:["Therefore","Moreover","For example"],
             ex:"前文講科技便利、這句話鋒一轉講壞處，用 However（然而）。誘答拆解：Therefore 因果、Moreover 遞進（要同方向）、For example 舉例——都無法完成「便利歸便利，但…」的轉折。"}),
        v=>({s:"Only when we put the phone down {N} how much time has passed.",
             c:"do we realize",d:["we realize","we do realize","realize we"],
             ex:"Only + 副詞子句放句首，主句要倒裝：Only when… do we realize。誘答拆解：we realize 未倒裝；we do realize 的 do 位置錯（助動詞要在主詞前）；realize we 完全錯亂。Only 開頭＝主句倒裝的訊號。"}) ],
      [ v=>({s:`Experts advise that screen time {N} strictly for children under ${v.age}.`,
             c:"be limited",d:["is limiting","limits","to limit"],
             ex:"advise/suggest/insist that + S + (should) + 原形——should 常省略，留下原形 be：that screen time (should) be limited；螢幕時間是「被限制」的對象故用被動。誘答拆解：is limiting／limits 是主動且未用原形；to limit 不定詞不能當 that 子句述語。"}),
        v=>({s:"Parents should decide {N} rules fit their family best.",
             c:"which",d:["who","whom","whose"],
             ex:"decide 後接名詞子句：which rules（哪些規則）當子句主詞——疑問形容詞 which + 名詞。誘答拆解：who／whom 指人且不能修飾 rules；whose 表「誰的」，語意不符（不是問規則屬於誰，而是問哪些規則）。"}) ],
      [ v=>({s:"Used wisely, technology {N} a bridge rather than a wall between people.",
             c:"can become",d:["becoming","become","to become"],
             ex:"主句需要完整述語：can become（可以成為）＝助動詞＋原形。句首 Used wisely 是分詞構句（＝If it is used wisely）。誘答拆解：becoming／to become 是非謂語形式；become 缺助動詞且與單數主詞不一致。"}),
        v=>({s:"The more we understand these tools, {N} we can use them.",
             c:"the better",d:["better","the best","good"],
             ex:"「越…越…」句型：The more…, the better…——兩個 the 缺一不可。誘答拆解：better 少了 the；the best 是最高級（此句型只收比較級）；good 是原級。此句型主詞動詞不倒裝，照常寫。"}) ]
    ]},

  /* ---------- CEEC ⑨ 節慶習俗 (lv1) ---------- */
  { kind:"ceec", cat:"word", lv:1,
    title:v=>"節慶記事："+v.festZh,
    lex:[
      {fest:"Dragon Boat Festival",festZh:"端午節",date:"the fifth day of the fifth lunar month",food:"rice dumplings",act:"boat races"},
      {fest:"Mid-Autumn Festival",festZh:"中秋節",date:"the fifteenth day of the eighth lunar month",food:"mooncakes",act:"lantern displays"},
      {fest:"Lunar New Year",festZh:"農曆新年",date:"the first day of the lunar calendar",food:"rice cakes",act:"lion dances"},
      {fest:"Lantern Festival",festZh:"元宵節",date:"the fifteenth day of the first lunar month",food:"sweet rice balls",act:"lantern displays"},
      {fest:"Double Ninth Festival",festZh:"重陽節",date:"the ninth day of the ninth lunar month",food:"chrysanthemum cakes",act:"mountain hikes"},
      {fest:"Winter Solstice",festZh:"冬至",date:"the shortest day of the year",food:"glutinous rice balls",act:"family dinners"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:`The ${v.fest} falls {N} ${v.date}.`,
             c:"on",d:["in","at","by"],
             ex:"特定的「日子」用 on（on the fifth day…）。誘答拆解：in 接月、年、季節等大範圍；at 接精確時刻；by 表「在…之前」的期限。時間介系詞由大到小：in → on → at。"}),
        v=>({s:"Families get together {N} the evening to share a big meal.",
             c:"in",d:["on","at","by"],
             ex:"in the evening（在晚上）是固定搭配——morning／afternoon／evening 用 in。誘答拆解：on 要配特定日子（on Friday evening 有指定星期才升級用 on）；at 配 night／noon／midnight；by 表期限。"}) ],
      [ v=>({s:`People enjoy {N} ${v.food} with family and friends.`,
             c:"eating",d:["to eat","eat","ate"],
             ex:"enjoy 只接動名詞：enjoy + V-ing。誘答拆解：enjoy to V 是最常見的錯誤答案；eat 原形、ate 過去式都不能當 enjoy 的受詞。同類：finish、avoid、mind、practice、suggest。"}),
        v=>({s:`Children look forward to {N} the ${v.act} every year.`,
             c:"watching",d:["watch","to watch","watched"],
             ex:"look forward to 的 to 是「介系詞」，後接 V-ing：look forward to watching。誘答拆解：watch 原形與 watched 過去式不能接在介系詞後；to watch 會造成 to to watch 的重複。這是介系詞 to 的三大金句之一（另兩個：be used to、object to）。"}) ],
      [ v=>({s:`The ${v.act}, {N} attract thousands of visitors, are the highlight of the day.`,
             c:"which",d:["that","who","where"],
             ex:"逗號後的非限定子句補充說明（物），用 which；非限定不可用 that。誘答拆解：who 指人；where 需接完整句子但這裡缺主詞。看到「逗號＋空格＋動詞」的組合，答案幾乎都是 which。"}),
        v=>({s:`It is a tradition {N} has been passed down for centuries.`,
             c:"that",d:["who","whose","when"],
             ex:"先行詞 a tradition（物）且子句缺主詞，用 that（或 which）。誘答拆解：who 指人；whose 是所有格；when 是關係副詞，需要接完整句子，但 has been passed down 前面缺主詞。"}) ],
      [ v=>({s:"{N} the weather is usually hot, the riverside is always packed with people.",
             c:"Although",d:["Because","Unless","So"],
             ex:"「天氣熱」與「人潮滿滿」語意對立（照理熱就不想出門），用讓步連接詞 Although。誘答拆解：Because 因果不通；Unless 是「除非」；So 不能放句首連接這種結構。"}),
        v=>({s:`For many people, the ${v.fest} is the {N} time of the whole year.`,
             c:"most exciting",d:["more exciting","exciting","excited"],
             ex:"the + 最高級 + of 範圍＝「整年之中最…的」：the most exciting time。誘答拆解：more exciting 是比較級；exciting 原級接不住 the…of the whole year 的「最」；excited 是「感到興奮的」（人的感受），不能形容 time——事物用 -ing、感受用 -ed。"}) ]
    ]},

  /* ---------- CEEC ⑩ 讀書方法 (lv2) ---------- */
  { kind:"ceec", cat:"clause", lv:2,
    title:v=>"讀書方法："+v.tipZh,
    lex:[
      {tipZh:"考前規劃"},{tipZh:"分段學習"},{tipZh:"教別人"},
      {tipZh:"筆記整理"},{tipZh:"睡眠與記憶"},{tipZh:"晨間複習"}
    ],
    intro:()=>"",
    outro:()=>"",
    slots:[
      [ v=>({s:"Before an exam, make a study plan {N} covers every subject.",
             c:"that",d:["who","whose","when"],
             ex:"先行詞 a study plan（物）且子句缺主詞（___ covers…），用 that（或 which）。誘答拆解：who 指人；whose 後接名詞；when 是關係副詞需接完整句——covers 前面缺主詞，所以用關代不用關副。"}),
        v=>({s:"Students {N} review a little every day usually feel less stressed before tests.",
             c:"who",d:["whose","which","whom"],
             ex:"先行詞 Students 指人、當子句主詞，用 who。誘答拆解：whose 是所有格；which 指物；whom 是受格。判斷步驟：先看先行詞是人是物，再看子句缺主詞還是受詞。"}) ],
      [ v=>({s:"If you study in short sessions, your brain {N} the information much better.",
             c:"will remember",d:["remembered","would remember","had remembered"],
             ex:"第一類條件句：If + 現在式（study），主句用 will + V。誘答拆解：remembered 過去式錯位；would remember 是第二類假設（暗示做不到，但分段讀書可行）；had remembered 是過去完成式，完全不在此時空。"}),
        v=>({s:"Unless you take short breaks, your focus {N} very quickly.",
             c:"will drop",d:["dropped","would have dropped","had dropped"],
             ex:"unless＝if…not（除非），同屬第一類條件句：主句用 will + V。誘答拆解：dropped 過去式；would have dropped 是第三類（與過去相反）；had dropped 過去完成式——本句講的是真實可能的未來。"}) ],
      [ v=>({s:"{N} helps many students most is explaining the material to a friend.",
             c:"What",d:["That","Which","It"],
             ex:"句首缺「自帶先行詞」的主詞——What＝the thing that（最有幫助的事）。誘答拆解：That 引導的子句必須完整（That he passed…），但這裡 helps 缺主詞；Which 需要先行詞；It 會讓後面的 is 沒有真正的主詞結構。口訣：句子完整用 That、缺角用 What。"}),
        v=>({s:"Write down the key points {N} you keep forgetting.",
             c:"that",d:["who","whose","when"],
             ex:"先行詞 key points（物）且子句缺「受詞」（forgetting ___），用 that（或 which，此處亦可省略）。誘答拆解：who 指人；whose 接名詞；when 需接完整句子——forgetting 缺受詞，證明要用關係代名詞。"}) ],
      [ v=>({s:"Get enough sleep the night before; {N}, you may forget what you studied.",
             c:"otherwise",d:["moreover","therefore","however"],
             ex:"「要睡飽，否則會忘光」——前句建議、後句是不照做的後果，用 otherwise（否則）。注意格式：分號＋otherwise＋逗號。誘答拆解：moreover 遞進、therefore 因果、however 轉折——只有 otherwise 帶有「若不然」的警告。"}),
        v=>({s:"Remember {N} your notes one last time on the morning of the test.",
             c:"to review",d:["reviewing","review","reviewed"],
             ex:"remember to V＝記得「去做」（還沒做的事）；考試早上的複習還沒發生，用 to review。誘答拆解：reviewing 變成「記得曾經複習過」；review／reviewed 缺 to 不成句型。remember／forget／stop 接 to V 或 V-ing 意思不同，是精熟級考點。"}) ]
    ]}
  ];

  /* ================= 組裝器 ================= */
  let n=0;
  FRAMES.forEach(fr=>{
    fr.lex.forEach((v,li)=>{
      for(let combo=0;combo<2;combo++){
        const sents=[], blanks=[]; let ok=true;
        fr.slots.forEach((slot,si)=>{
          const pick=slot[(combo+si+li)%slot.length];
          const def=pick(v);
          if(!def||!def.c||!def.d||!def.d.length||!def.ex){ ok=false; return; }
          sents.push(def.s.replace('{N}','{'+(si+1)+'}'));
          const opts=[String(def.c),...def.d.map(String)];
          if(new Set(opts).size!==opts.length){ ok=false; return; }
          for(let i=opts.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [opts[i],opts[j]]=[opts[j],opts[i]]; }
          blanks.push({opts,a:opts.indexOf(String(def.c)),ex:def.ex});
        });
        if(!ok||blanks.length!==4) continue;
        const text=(fr.intro&&fr.intro(v)?fr.intro(v)+"\n\n":"")+sents.join(" ")+(fr.outro&&fr.outro(v)?"\n\n"+fr.outro(v):"");
        OUT.push({id:"clz-"+(n++),kind:fr.kind,cat:fr.cat,lv:fr.lv,title:fr.title(v),text,blanks});
      }
    });
  });

  window.CLOZE=(window.CLOZE||[]).concat(OUT);
})();
